name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yikesdocker/linux-kernel-reading-lib:1.0.0
      
    - name: Log into registry
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u yikesdocker --password-stdin
    - name: push to dockerhub
      run: |
        docker push yikesdocker/linux-kernel-reading-lib:1.0.0

